"""Add tracking type to Exercise model

Revision ID: 08f2ee178c67
Revises: d0a1cdaa4323
Create Date: 2026-06-20 21:01:39.415525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f2ee178c67'
down_revision = 'd0a1cdaa4323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_type', sa.String(length=50), nullable=False, server_default="weighted_reps"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('tracking_type')

    # ### end Alembic commands ###
