"""add is_dumbbell_pair to exercises

Revision ID: 5cb9f6709114
Revises: 97501465d46b
Create Date: 2026-07-15 11:13:38.333583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb9f6709114'
down_revision = '97501465d46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_dumbbell_pair', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('is_dumbbell_pair')

    # ### end Alembic commands ###
